@startuml
'https://plantuml.com/sequence-diagram

autonumber

Input_Loop --> User_Input: Try/Catch if input is a number.
User_Input --> Input_Loop: Saves input into double array.
Input_Loop --> Input_Loop: Loop five times.


Input_Loop -> Output: Output for loop adds array values for total.
Output -> Output: Prints out total onto console.

@enduml