@startuml
'https://plantuml.com/sequence-diagram

autonumber

Input_Loop --> Try_Catch: Checks to see if input is a number.
Try_Catch --> User_Input: Saves input into double array.
User_Input --> Input_Loop: Loops until fifth time.


Input_Loop -> Output_Loop: Adds user_input[ ] to output variable for total.
Output_Loop -> Answer: Prints out total on to console.

@enduml